//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTunes.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP3
    {
        public MP3()
        {
            this.Playlist = new HashSet<Playlist>();
        }
    
        public int MP3ID { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public string Album { get; set; }
        public Nullable<short> Year { get; set; }
    
        public virtual ICollection<Playlist> Playlist { get; set; }
    }
}
