//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTunes.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist
    {
        public Playlist()
        {
            this.MP3 = new HashSet<MP3>();
        }
    
        public int PlaylistID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MP3> MP3 { get; set; }
    }
}
