
CREATE TABLE [dbo].[MP3Playlist](
	[MP3ID] [int] NOT NULL,
	[PlaylistID] [int] NOT NULL,
 CONSTRAINT [PK_MP3Playlist] PRIMARY KEY CLUSTERED 
(
	[MP3ID] ASC,
	[PlaylistID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MP3Playlist]  WITH CHECK ADD  CONSTRAINT [FK_MP3Playlist_MP3] FOREIGN KEY([MP3ID])
REFERENCES [dbo].[MP3] ([MP3ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[MP3Playlist] CHECK CONSTRAINT [FK_MP3Playlist_MP3]
GO

ALTER TABLE [dbo].[MP3Playlist]  WITH CHECK ADD  CONSTRAINT [FK_MP3Playlist_Playlist] FOREIGN KEY([PlaylistID])
REFERENCES [dbo].[Playlist] ([PlaylistID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[MP3Playlist] CHECK CONSTRAINT [FK_MP3Playlist_Playlist]
GO

